### ISSUE TITLE
Feature request: Use variable amount of args instead of fixed amount

### ISSUE THREAD

**Issue by mdev88** [xyb/googlesearch.nim#1]
Hello, I am playing around with googlesearch, and I find that having to use "quotes" to inclose my query is a limitation, because sometimes I need to inclose a part of the query inside quotes, and leave another part out, for example:

`"this goes together" -something site:somesite.com`

It would be great if googlesearch used a variable amount of arguments instead of taking just 2, so in that case it should take all the arguments except the last one as the query, and use the last one as the number of pages to display.

Cheers.

**Comment by mdev88** [comment]
I think that I can escape the " with \\", so I would use something like this:

`googlesearch "\"this goes together\" -something site:somesite.com" 5`

but anyway, I would find it more easy to understand if I could use:

`googlesearch "this goes together" -something site:somesite.com 5`

**Comment by xyb** [comment]
@mdev88 Thank you for your advice. It's complicated. Shell, bash etc, will *eat* enclosing characters like `"` or `'`. You can not simply retrieval command line argument string of user input even in C language, nim have not a good way to do that neither. You can read it with os-specialized solutions, for example, procfs in linux, but it's way too far to do search things, I have a simpler solution: put all search terms into first argument. You chould run a search like:
`googlesearch '"this goes together" -something site:somesite.com' 5`
that's easy and reliable. That works for me.

**Comment by mdev88** [comment]
Excellent, thanks.
